= Story Class Service
Christopher Little <christopher@story-ai.com>
:imagesdir: assets

This service provides proxy access to teacher/manager api methods on CENTURY.
It works by logging in using a teacher account's username and password, and 
then using the returned API token to make subsequent requests.
It is mostly written in TypeScript. 

== Documentation

The API is (loosely) documented with an
https://github.com/OAI/OpenAPI-Specification[OpenAPI] specification, which is
served on the `{service-base}/spec` endpoint. We currently use this specification to 
generate automated documentation, but it will also be used to generate client libraries.

Sample Service:: 
http://petstore.swagger.io/?url=https://api.story-ai.com/class/spec[Documentation]
(https://api.story-ai.com/class/spec[specification])

== Run it yourself

This service runs on a serverless architecture (currently targeting AWS),
and is managed with the https://serverless.com/[Serverless Framework]. We
take advantage of the
https://github.com/dherault/serverless-offline[serverless-offline] plugin for
rapid development without deployment.

=== Installation

```
npm install serverless -g                                   
git clone git@github.com:story-ai/class-service.git
cd class-service
npm install                                                 
vim keys.yml    # Edit to add correct credentials and API keys
```

=== Local
```
serverless offline
```

=== Deploy to AWS
http://docs.aws.amazon.com/cli/latest/userguide/installing.html[Install]
and http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html[configure] the AWS cli.
Then run: 

```
serverless deploy
```

